// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dlfztrxnkfozxqebngxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZnp0cnhua2ZvenhxZWJuZ3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDQwOTUsImV4cCI6MjA2NzgyMDA5NX0.MDGAW5GrUZNFMskzkePK3dwK94wcIIDMLCJmVSpzyW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);